"""add businesses uploads sales_facts

Revision ID: 6c4c2fd36cf7
Revises: 0fcaf29628e4
Create Date: 2026-01-10 17:24:08.531887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4c2fd36cf7'
down_revision: Union[str, Sequence[str], None] = '0fcaf29628e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_user_id'), 'businesses', ['user_id'], unique=True)
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_business_id'), 'uploads', ['business_id'], unique=False)
    op.create_index(op.f('ix_uploads_file_hash'), 'uploads', ['file_hash'], unique=False)
    op.create_table('sales_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('ds', sa.Date(), nullable=False),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_facts_business_id'), 'sales_facts', ['business_id'], unique=False)
    op.create_index(op.f('ix_sales_facts_ds'), 'sales_facts', ['ds'], unique=False)
    op.create_index(op.f('ix_sales_facts_item'), 'sales_facts', ['item'], unique=False)
    op.create_index(op.f('ix_sales_facts_upload_id'), 'sales_facts', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_facts_upload_id'), table_name='sales_facts')
    op.drop_index(op.f('ix_sales_facts_item'), table_name='sales_facts')
    op.drop_index(op.f('ix_sales_facts_ds'), table_name='sales_facts')
    op.drop_index(op.f('ix_sales_facts_business_id'), table_name='sales_facts')
    op.drop_table('sales_facts')
    op.drop_index(op.f('ix_uploads_file_hash'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_business_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_businesses_user_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
